#!/bin/sh
# ship: Ship current branch to development branch

source "$(git --exec-path)/git-sh-setup"

if [ -z "$1" ]
then
	die "You must supply a message for the squashed commit"
fi

currentBranch=$(git symbolic-ref HEAD 2>/dev/null --short)

if [ "${currentBranch}" == "master" ]
then
	die "You can not ship from master"
fi

git svn update || { die "Updating from SVN failed"; }
git svn dcommit || { die "Pushing to SVN failed"; }
git checkout master
git branch -d "${currentBranch}" || { die "Removing ${currentBranch} failed"; }