#!/bin/sh
# Merge the latest changes from the master branch into your current branch

source "$(git --exec-path)/git-sh-setup"

currentBranch=$(git symbolic-ref HEAD 2>/dev/null --short)

# echo "$(tput setaf 6)Stashing any current changes on branch$(tput sgr0)"
# git stash save
echo "$(tput setaf 6)Pulling latest remote changes into master$(tput sgr0)"
git checkout master
git svn rebase
echo "$(tput setaf 6)Rebasing ${currentBranch} with the new changes from master$(tput sgr0)"
git checkout ${currentBranch}
git rebase master
# echo "$(tput setaf 6)Reapplying any stashed changes$(tput sgr0)"
# git stash pop