#!/bin/sh
# ship: Ship current branch to development branch

source "$(git --exec-path)/git-sh-setup"

currentBranch=$(git symbolic-ref HEAD 2>/dev/null --short)

if [ "${currentBranch}" == "master" ]
then
	die "You can not ship from master"
fi

git svn_update || { die "Updating from SVN failed"; }

echo "$(tput setaf 6)Committing changes to SVN$(tput sgr0)"
git svn dcommit || { die "Pushing to SVN failed"; }

echo "$(tput setaf 6)Updating master$(tput sgr0)"
git checkout master
git svn rebase

echo "$(tput setaf 6)Removing ${currentBranch}$(tput sgr0)"
git branch -d "${currentBranch}" || { die "Removing ${currentBranch} failed"; }