#!/bin/sh
# Merge the latest changes from the master branch into your current branch

source "$(git --exec-path)/git-sh-setup"

currentBranch=$(git symbolic-ref HEAD 2>/dev/null --short)

if tput setaf 1 &> /dev/null; then
    tput sgr0
    if [[ $(tput colors) -ge 256 ]] 2>/dev/null; then
      MAGENTA=$(tput setaf 9)
      ORANGE=$(tput setaf 172)
      GREEN=$(tput setaf 190)
      PURPLE=$(tput setaf 141)
      WHITE=$(tput setaf 256)
    else
      MAGENTA=$(tput setaf 5)
      ORANGE=$(tput setaf 4)
      GREEN=$(tput setaf 2)
      PURPLE=$(tput setaf 1)
      WHITE=$(tput setaf 7)
    fi
    BOLD=$(tput bold)
    RESET=$(tput sgr0)
else
    MAGENTA="\033[1;31m"
    ORANGE="\033[1;33m"
    GREEN="\033[1;32m"
    BLUE="\033[1;34m"
    PURPLE="\033[1;35m"
    WHITE="\033[1;37m"
    BOLD=""
    RESET="\033[m"
fi

# echo "$(tput setaf 6)Stashing any current changes on branch$(tput sgr0)"
# git stash save
echo "\[$BLUE\]Pulling latest remote changes into master\[$RESET\]"
git checkout master
git svn rebase
echo "\[$BLUE\]Rebasing ${currentBranch} with the new changes from master\[$RESET\]"
git checkout ${currentBranch}
git rebase master
# echo "$(tput setaf 6)Reapplying any stashed changes$(tput sgr0)"
# git stash pop